INSERT INTO list_items (category, value, sort_order) VALUES
    ('status_fulltime', 'Wishlist', 1),
    ('status_fulltime', 'Apply', 2),
    ('status_fulltime', 'Screening HR', 3),
    ('status_fulltime', 'Interview HR', 4),
    ('status_fulltime', 'Interview User', 5),
    ('status_fulltime', 'Interview Final', 6),
    ('status_fulltime', 'Technical Test', 7),
    ('status_fulltime', 'Offer', 8),
    ('status_fulltime', 'Diterima', 9),
    ('status_fulltime', 'Ditolak', 10),
    ('status_fulltime', 'Ghosting', 11),
    ('status_fulltime', 'Withdraw', 12),
    ('sumber_fulltime', 'LinkedIn', 1),
    ('sumber_fulltime', 'JobStreet', 2),
    ('sumber_fulltime', 'Glints', 3),
    ('sumber_fulltime', 'Kalibrr', 4),
    ('sumber_fulltime', 'Dealls', 5),
    ('sumber_fulltime', 'Website Perusahaan', 6),
    ('sumber_fulltime', 'Referral', 7),
    ('sumber_fulltime', 'Recruiter DM', 8),
    ('sumber_fulltime', 'Job Fair', 9),
    ('sumber_fulltime', 'Lainnya', 10),
    ('tipe_kerja', 'WFO', 1),
    ('tipe_kerja', 'WFH / Remote', 2),
    ('tipe_kerja', 'Hybrid', 3),
    ('prioritas', 'Tinggi', 1),
    ('prioritas', 'Sedang', 2),
    ('prioritas', 'Rendah', 3),
    ('status_freelance', 'Lead', 1),
    ('status_freelance', 'Proposal Terkirim', 2),
    ('status_freelance', 'Negosiasi', 3),
    ('status_freelance', 'Deal / DP', 4),
    ('status_freelance', 'Dikerjakan', 5),
    ('status_freelance', 'Review Klien', 6),
    ('status_freelance', 'Selesai', 7),
    ('status_freelance', 'Batal', 8),
    ('status_freelance', 'Ghosting', 9),
    ('sumber_freelance', 'Referral', 1),
    ('sumber_freelance', 'Upwork', 2),
    ('sumber_freelance', 'Fiverr', 3),
    ('sumber_freelance', 'Sribulancer', 4),
    ('sumber_freelance', 'Projects.co.id', 5),
    ('sumber_freelance', 'LinkedIn', 6),
    ('sumber_freelance', 'Komunitas / Discord', 7),
    ('sumber_freelance', 'Teman / Eks Kantor', 8),
    ('sumber_freelance', 'Lainnya', 9),
    ('status_bayar', 'Belum Ditagih', 1),
    ('status_bayar', 'Invoice Terkirim', 2),
    ('status_bayar', 'DP Masuk', 3),
    ('status_bayar', 'Lunas', 4),
    ('status_bayar', 'Telat Bayar', 5),
    ('status_bayar', 'Macet', 6),
    ('stack', 'Laravel', 1),
    ('stack', 'Golang', 2),
    ('stack', 'Next.js', 3),
    ('stack', 'React', 4),
    ('stack', 'Fullstack', 5),
    ('stack', 'API / Backend', 6),
    ('stack', 'Landing Page', 7),
    ('stack', 'Maintenance', 8),
    ('stack', 'Lainnya', 9)
ON CONFLICT (category, value) DO NOTHING;

INSERT INTO dashboard_targets (metric_key, target_value) VALUES
    ('perusahaan_dilamar', 5),
    ('masuk_interview', 3),
    ('lolos_interview2', 2),
    ('offer_diterima', 1),
    ('freelance_closing', 1)
ON CONFLICT (metric_key) DO NOTHING;
